
# load_data.py
# Minimal script: prompt for a JSON/JSONL file and load into PostgreSQL.
# Expects already-clean data and a flat object per row.
# Table: applicants (single table), columns exactly as specified.
# No extra validation or error handling by design.

import json
import psycopg2

# --- Prompts ---
json_path = input("Path to JSON (.json) or JSON Lines (.jsonl/.ndjson): ").strip()
host = input("PostgreSQL host [localhost]: ").strip() or "localhost"
port = int(input("PostgreSQL port [5432]: ").strip() or "5432")
dbname = input("Database name: ").strip()
user = input("User: ").strip()
password = input("Password: ").strip()

# --- Read input ---
records = []
if json_path.lower().endswith((".jsonl", ".ndjson")):
    with open(json_path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
else:
    with open(json_path, "r", encoding="utf-8") as f:
        records = json.load(f)

# --- DB connect ---
conn = psycopg2.connect(host=host, port=port, dbname=dbname, user=user, password=password)
cur = conn.cursor()

# --- Create table ---
cur.execute("""
    CREATE TABLE IF NOT EXISTS applicants (
        p_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        program TEXT,
        comments TEXT,
        date_added DATE,
        url TEXT,
        status TEXT,
        term TEXT,
        us_or_international TEXT,
        gpa REAL,
        gre REAL,
        gre_v REAL,
        gre_aw REAL,
        degree REAL,
        llm_generated_program TEXT,
        llm_generated_university TEXT
    );
""")

# --- Insert rows ---
columns = [
    "program","comments","date_added","url","status","term",
    "us_or_international","gpa","gre","gre_v","gre_aw","degree",
    "llm_generated_program","llm_generated_university"
]
cols_noid = [
    'program','comments','date_added','url','status','term',
    'us_or_international','gpa','gre','gre_v','gre_aw','degree',
    'llm_generated_program','llm_generated_university'
]
placeholders = ",".join(["%s"]*len(columns))
sql = f"INSERT INTO applicants ({','.join(columns)}) VALUES ({placeholders});"

for rec in records:
    cur.execute(sql, [rec.get(c) for c in columns])

conn.commit()
cur.close()
conn.close()
print("Done.")
